local config = {
  layout_config = {
    vertical = {
      mirror = false,
      preview_height = 28,
    },
    width = 0.6,
    height = 0.9,
    preview_cutoff = 10,
  },
  ctags = {'ctags'},
  ft_opt = {
    aspvbs = '--asp-kinds=f',
    awk = '--awk-kinds=f',
    c = '--c-kinds=fp',
    cpp = '--c++-kinds=fp --language-force=C++',
    cs = '--c#-kinds=m',
    erlang = '--erlang-kinds=f',
    fortran = '--fortran-kinds=f',
    java = '--java-kinds=m',
    javascript = '--javascript-kinds=f',
    lisp = '--lisp-kinds=f',
    lua = '--lua-kinds=f',
    matla = '--matlab-kinds=f',
    pascal = '--pascal-kinds=f',
    php = '--php-kinds=f',
    python = '--python-kinds=fm --language-force=Python',
    ruby = '--ruby-kinds=fF',
    scheme = '--scheme-kinds=f',
    sh = '--sh-kinds=f',
    sql = '--sql-kinds=f',
    tcl = '--tcl-kinds=m',
    verilog = '--verilog-kinds=f',
    vim = '--vim-kinds=f',
    go = '--go-kinds=f',
    rust = '--rust-kinds=fPM',
    ocaml = '--ocaml-kinds=mf',
  },
}

return config
